name: rentall
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^8.1.1
  get_it: ^7.2.0
  image_picker: ^0.8.4+11
  internet_connection_checker: ^0.0.1+3
  json_annotation: ^4.5.0
  phone_number: ^0.12.0+2
  shared_preferences: ^2.0.13
  url_launcher: ^6.1.0
  flutter_facebook_auth: ^4.3.4
  google_sign_in: ^5.3.1
  algolia: ^1.1.1

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
